### PR TITLE
Update Place Sabah As Salem

### PR DESCRIPTION
**Pull request by iandees**
Updating `data/421/189/037/421189037.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by thisisaaronland** [comment]
`edtf:deprecated` and `edtf:superseded` should only be present when they are non-empty.

**Comment by thisisaaronland** [comment]
`mz:max_zoom` should be an int (float) rather than a string.

**Comment by thisisaaronland** [comment]
`"wof:shortcode":"ian"` ?

**Comment by thisisaaronland** [comment]
`mz:is_current` should be a (signed) int.

**Comment by iandees** [comment]
This was an initial test of the code to create a PR. I'll fix these formatting things, but it might make sense to lean on exportify to make these changes for us?

**Comment by thisisaaronland** [comment]
Yes, that is what `py-mz-wof-export` is for. It also handles formatting.

**Comment by iandees** [comment]
I'm running the document through https://github.com/whosonfirst/py-mapzen-whosonfirst-export/ (specifically https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L70) before sending it to GitHub to create the pull request.

**Pull request closed without merging**
