### PR TITLE
Updated admin records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1912.

To do:
- [x] Update region records with new properties and geometries
- [x] Update county records with new properties and geometries
  - [x]  These are placetype "fillers", so flag as coterminous w region parents
  - [x] Deprecate two bunk county records
  - [x] ~Flag as statistical gore?~ (flagged as coterminous)
  - [x] Create two new county records
- [x] Update locality records
  - [x] Add missing localities
  - [x] Update existing localities
  - [x] Clean up leftovers
    - Leftover locality points that fell outside of new locality polygons were generally left untouched
    - Leftover locality points that fell within new locality polygons were deprecated and flagged as not current.
- [x] Update neighbourhood records
  - [x] Add missing neighbourhoods
  - [x] Update existing neighbourhoods
  - [x] Clean up leftovers (deprecated, flagged as not current, or moved to microhood)
    - Leftover neighbourhood points were either deprecated and flagged as not current, or moved to a microhood placetype (sub-block level records were moved to the microhood placetype).
    - Leftover locality points that fell within new locality polygons were flagged as not current.
- [x] Update campus record(s?)
- [ ] Validate
- [x] PIP

Related: https://github.com/whosonfirst-data/whosonfirst-data-admin-xy/pull/25

### CODE REVIEW

**Comment by stepps00** [comment]
Commit Notes:
- aa50644: Updates each region with a new geometry, updates names, labels, and concordances
- 093090d: Deprecates two existing county records that are not legitimate admin2 in Kuwait

**Comment by stepps00** [comment]
Some screenshots of the new geometries, visualized in QGIS:

**Regions**
Screen Shot 2021-01-19 at 4 52 02 PM

**Counties**
Screen Shot 2021-01-19 at 4 52 20 PM

**Localities**
Screen Shot 2021-01-19 at 4 52 31 PM

**Neighbourhoods**
Screen Shot 2021-01-19 at 4 52 41 PM

**Comment by stepps00** [comment]
@nvkelso this PR is ready for review; I have exports of each placetype ready to QA. If all looks good, I'll validate, PIP, and merge.

**Comment by stepps00** [comment]
@nvkelso I've added a new commit to this PR to flag a handful of "leftover" locality points that fall within new locality polygons as not current. These records don't match to neighbourhoods, so rather than reclassify them at a new placetype or flag w `mz:is_funky`, they've been deprecated.

This PR is ready for review.

**Comment by stepps00** [comment]
PIP work completed in the most recent commit.

**Review by nvkelso — APPROVED** [review]

**Comment by stepps00** [comment]
QA'd once more, all geometries look good. Merging.

**Pull request merged**
